###
GET http://localhost:3000/api/employees

###
POST http://localhost:3000/api/employees
Content-Type: application/json

{
    "name": "Ryan Ray",
    "position": "Snr. Developer",
    "office": "Rome",
    "salary": "22000"
}

###
GET http://localhost:3000/api/employees/632ae7ddb73d930593a3dd30

###
PUT http://localhost:3000/api/employees/632ae7ddb73d930593a3dd30
Content-Type: application/json

{
    "name": "Joe McMillan",
    "position": "Digital Marketing Manager",
    "office": "California",
    "salary": "20000"
}

###
DELETE http://localhost:3000/api/employees/632ae815b73d930593a3dd33